name: Lint Docs

on:
  pull_request:
    branches:
      - main

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Vale
        uses: errata-ai/vale-action@v2
        continue-on-error: true
        with:
          files: '["docs", "README.md"]'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
